# this indicates the version of the node image you wanna use. i.e Use the version of this node image. 
FROM node:alpine


# Tells Docker to create this directory such that subsequent commands will use the directory. 
WORKDIR /app   


# Copy our package.json into the /app directory we created. It tells node what modules we wanna use. 
COPY package.json  /app

# To install the dependencies the app needs inside of the Image.

RUN yarn install

# It copies everything in the local directory into the image in the code directory */
COPY . /app

# To navigate the application's entry point and run the image. 

CMD ["yarn","run", "start"]  
